objects/CalSTA_Reassign_Comments__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ProcessStepId__c</fullName>
        <label>ProcessStepId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TargetObjectId__c</fullName>
        <label>TargetObjectId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>CalSTA Reassign Comments</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CalSTA Reassign Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Action_requested__c</fullName>
        <label>Action Requested</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>For Information Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Constituent_Address__c</fullName>
        <label>Constituent Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Constituent_Email__c</fullName>
        <label>Constituent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Constituent_Name__c</fullName>
        <label>Constituent Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Constituent_Phone__c</fullName>
        <label>Constituent Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Date_CalSTA_Received_from_GO__c</fullName>
        <label>Date CalSTA Received from GO</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Due__c</fullName>
        <inlineHelpText>Click the calendar icon to select a date or enter using the format mm/dd/yyyy</inlineHelpText>
        <label>Date Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Due_to_CALSTA__c</fullName>
        <label>Date Due to CalSTA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Due_to_the_GO__c</fullName>
        <label>Date Due to the GO</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <formula>DATEVALUE(CreatedDate)</formula>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Received_by_CalSTA__c</fullName>
        <inlineHelpText>Click the calendar icon to select a date or enter using the format mm/dd/yyyy</inlineHelpText>
        <label>Date Received by CalSTA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Revision_Due_Back_From_Dept__c</fullName>
        <inlineHelpText>Click the calendar icon to select a date or enter using the format mm/dd/yyyy</inlineHelpText>
        <label>Date Revision Due Back From Dept</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Correspondence__c</fullName>
        <label>Date of Correspondence</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_IM__c</fullName>
        <inlineHelpText>Click the calendar icon to select a date or enter using the format mm/dd/yyyy</inlineHelpText>
        <label>Date of IM</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Transmittal__c</fullName>
        <label>Date of Transmittal</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_Overdue__c</fullName>
        <formula>IF( Request_Due_Date__c &lt; TODAY(), 

CASE(MOD( Request_Due_Date__c - DATE(1985,6,24),7), 
  0 , CASE( MOD( TODAY()-Request_Due_Date__c,7),1,2,2,3,3,4,4,5,5,5,6,5,1), 
  1 , CASE( MOD( TODAY()-Request_Due_Date__c,7),1,2,2,3,3,4,4,4,5,4,6,5,1), 
  2 , CASE( MOD( TODAY()-Request_Due_Date__c,7),1,2,2,3,3,3,4,3,5,4,6,5,1), 
  3 , CASE( MOD( TODAY()-Request_Due_Date__c,7),1,2,2,2,3,2,4,3,5,4,6,5,1), 
  4 , CASE( MOD( TODAY()-Request_Due_Date__c,7),1,1,2,1,3,2,4,3,5,4,6,5,1), 
  5 , CASE( MOD( TODAY()-Request_Due_Date__c,7),1,0,2,1,3,2,4,3,5,4,6,5,0), 
  6 , CASE( MOD( TODAY()-Request_Due_Date__c,7),1,1,2,2,3,3,4,4,5,5,6,5,0), 
  999) 
  + 
  (FLOOR(( TODAY() - Request_Due_Date__c )/7)*5)-1

,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Overdue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_overdue_to_Eventual_Recipient__c</fullName>
        <formula>IF( Due_Date_to_Eventual_Recipient__c &lt; TODAY(),
CASE(MOD(Due_Date_to_Eventual_Recipient__c  - DATE(1985,6,24),7), 0 , 
CASE( MOD( Today() - Due_Date_to_Eventual_Recipient__c  ,7),1,2,2,3,3,4,4,5,5,5,6,5,1), 1, 
CASE( MOD( Today() - Due_Date_to_Eventual_Recipient__c  ,7),1,2,2,3,3,4,4,4,5,4,6,5,1), 2, 
CASE( MOD( Today() - Due_Date_to_Eventual_Recipient__c  ,7),1,2,2,3,3,3,4,3,5,4,6,5,1), 3, 
CASE( MOD( Today() - Due_Date_to_Eventual_Recipient__c  ,7),1,2,2,2,3,2,4,3,5,4,6,5,1), 4 , 
CASE( MOD( Today() - Due_Date_to_Eventual_Recipient__c  ,7),1,1,2,1,3,2,4,3,5,4,6,5,1), 5 , 
CASE( MOD( Today() - Due_Date_to_Eventual_Recipient__c  ,7),1,0,2,1,3,2,4,3,5,4,6,5,0), 6 , 
CASE( MOD( Today() - Due_Date_to_Eventual_Recipient__c  ,7),1,1,2,2,3,3,4,4,5,5,6,5,0),999) 
  + 
(FLOOR(( Today() - Due_Date_to_Eventual_Recipient__c )/7)*5)-1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days overdue to Eventual Recipient</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Department_Sent_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department Sent To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date_to_Eventual_Recipient__c</fullName>
        <label>Due Date to Eventual Recipient</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Eventual_recipient_if_differ_than_above__c</fullName>
        <inlineHelpText>Eventual recipient if different than above</inlineHelpText>
        <label>Recipient if different than above</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GO_Tracking_Number__c</fullName>
        <label>GO Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initially_Due_To__c</fullName>
        <label>Initially Due To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Governor’s Office</fullName>
                </value>
                <value>
                    <fullName>Bureau of State Audits</fullName>
                </value>
                <value>
                    <fullName>Department of Finance</fullName>
                </value>
                <value>
                    <fullName>Department of General Services</fullName>
                </value>
                <value>
                    <fullName>Department for Rulemaking Process</fullName>
                </value>
                <value>
                    <fullName>Office of Administrative Law</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Instructions_to_the_Department__c</fullName>
        <description>Instructions to Department</description>
        <label>Instructions to Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reply direct and furnish to CalSTA with copies</fullName>
                </value>
                <value>
                    <fullName>Prepare for signature of return with the attached</fullName>
                </value>
                <value>
                    <fullName>Notify CalSTA of action taken</fullName>
                </value>
                <value>
                    <fullName>Handle as indicated above (return all suggested replies to CalSTA)</fullName>
                </value>
                <value>
                    <fullName>Reply direct and furnish GO and CalSTA with copies</fullName>
                    <isActive>false</isActive>
                    <label>Reply direct and furnish GO and CalSTA with copies</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issue_Memo_Type__c</fullName>
        <label>Issue Memo Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IT PAL</fullName>
                    <label>IT-PAL</label>
                </value>
                <value>
                    <fullName>IT Procurement</fullName>
                    <label>IT-Procurement</label>
                </value>
                <value>
                    <fullName>IT Miscellaneous</fullName>
                    <label>IT-Miscellaneous</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Days_Overdue__c</fullName>
        <formula>IF ( Date_Due_to_CALSTA__c &lt; TODAY(),

CASE(MOD( Date_Due_to_CALSTA__c  - DATE(1985,6,24),7), 
0 , CASE( MOD( Today() - Date_Due_to_CALSTA__c  ,7),1,2,2,3,3,4,4,5,5,5,6,5,1), 
1 , CASE( MOD( Today() - Date_Due_to_CALSTA__c ,7),1,2,2,3,3,4,4,4,5,4,6,5,1), 
2 , CASE( MOD( Today() - Date_Due_to_CALSTA__c  ,7),1,2,2,3,3,3,4,3,5,4,6,5,1), 
3 , CASE( MOD( Today() - Date_Due_to_CALSTA__c ,7),1,2,2,2,3,2,4,3,5,4,6,5,1), 
4 , CASE( MOD( Today() - Date_Due_to_CALSTA__c  ,7),1,1,2,1,3,2,4,3,5,4,6,5,1), 
5 , CASE( MOD( Today() - Date_Due_to_CALSTA__c  ,7),1,0,2,1,3,2,4,3,5,4,6,5,0), 
6 , CASE( MOD( Today() - Date_Due_to_CALSTA__c  ,7),1,1,2,2,3,3,4,4,5,5,6,5,0), 
999) 
+ 
(FLOOR(( Today() - Date_Due_to_CALSTA__c )/7)*5)-1
,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Days Overdue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_to_Red_Flag_Issue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Related to Red Flag Issue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Due_Date__c</fullName>
        <inlineHelpText>Click the calendar icon to select a date or enter using the format mm/dd/yyyy</inlineHelpText>
        <label>Request Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revision_of_Previous_version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Revision of Previous version</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitted_Duplicate_Correspondence__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted Duplicate Correspondence</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <externalId>true</externalId>
        <label>CALSTA Tracking Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transmitting_Mandated_Report__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transmitting Mandated Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Under_review_or_being_processed_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Under review or being processed by</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CalSTA_Pdf_Generation_Controller.cls
/**
*--------------------------------------------------------------------------------------
* Version#     Date                           Author                    Description
*--------------------------------------------------------------------------------------
*    1.0      07-OCT-2019                   GTP Dev Team               Initial Version
*--------------------------------------------------------------------------------------
*/
public class CalSTA_Pdf_Generation_Controller {    
    public Case caseobj{get;set;} 
    public account department{get;set;}
    public String recordTypeName{get;set;} 
    public Map<String,boolean> instructionPickListValuesList {get;set;}
    public Boolean isInstructionValid{get;set;}
    public Boolean isSectionVisible{get;set;}   
    public String initialDuetoText{get;set;}
    public List<ApprovalHistoryWrapper> approvalHistoryWrapperList{get;set;}
    
    /** 
    * __________________________________________________________________________
    * 
    * This constructor is used to display data in Print PDF
    * __________________________________________________________________________
    */
    public CalSTA_Pdf_Generation_Controller(){              
        
        
        string recordId = ApexPages.currentPage().getParameters().get('id');       
            
            caseobj =[SELECT Id,RecordTypeId,Department_Sent_To__c,Account.Name,Date_Received_by_CalSTA__c,Issue_Memo_Type__c,Request_Due_Date__c  ,Related_to_Red_Flag_Issue__c,Transmitting_Mandated_Report__c ,Revision_of_Previous_version__c,Eventual_recipient_if_differ_than_above__c, Due_Date_to_Eventual_Recipient__c, Days_overdue_to_Eventual_Recipient__c, Date_Completed__c,Date_Due_to_CALSTA__c,Date_of_IM__c,Under_review_or_being_processed_by__c ,Date_Revision_Due_Back_From_Dept__c  ,Date_Received__c ,Subject , Tracking_Number__c, CreatedDate, Date_Due__c, Initially_Due_To__c,Days_Overdue__c, Number_of_Days_Overdue__c,Action_requested__c ,CreatedBy.Name, Status, GO_Tracking_Number__c, Date_Due_to_the_GO__c, Date_CalSTA_Received_from_GO__c, Constituent_Name__c, Constituent_Address__c, Constituent_Phone__c, Constituent_Email__c, Date_of_Correspondence__c, Date_of_Transmittal__c, Submitted_Duplicate_Correspondence__c, Instructions_to_the_Department__c FROM Case Where Id=: recordId];
            if(caseobj.Department_Sent_To__c !=null){
                department = [SELECT Id,Name FROM account where Id =: caseobj.Department_Sent_To__c];            
            }
            
            RecordType rtype = [SELECT Name, DeveloperName, Id FROM RecordType where id=:caseobj.RecordTypeId];
            recordTypeName = rtype.Name;
            isSectionVisible =true;
            if(recordTypeName == 'Constituent Concern'){
                isSectionVisible =false;
            }
            if(recordTypeName == 'Governor’s Office Action Request (GOAR)' || recordtypename == 'Governor’s Office Action Request (GOAR)-Scheduling' || recordtypename == 'Governor’s Office Action Request – Legal (GOAR)' ){           
                initialDuetoText = 'Governors Office';    
            }
        	
           /** 
             * _______________________________________________________
             * 
             * Getting Instruction to department picklist values 
             * ________________________________________________________
             */
            Map<String,boolean> pickListValuesList = new Map<String,boolean>();
            Schema.DescribeFieldResult fieldResult = Case.Instructions_to_the_Department__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                isInstructionValid = false;
                if(pickListVal.getLabel() == caseobj.Instructions_to_the_Department__c ){
                    isInstructionValid = true; 
                }                          
                pickListValuesList.put(pickListVal.getLabel(),isInstructionValid);
            }                      
            instructionPickListValuesList = pickListValuesList;    
            approvalHistoryWrapperList = getApprovalHistoryList(recordId);
    }
    
    /** 
    * __________________________________________________________________________
    * 
    * This method is used for checking if logged user is department user or not
    * __________________________________________________________________________
    */
	@AuraEnabled
    public static Boolean departmentUser(){
          Boolean isDepartmentUser=false;
         String departmentUserProfile = [select Name from profile where id =: userinfo.getProfileId()].Name;
        if(departmentUserProfile =='Department User'){
            isDepartmentUser=true;
        }
        return isDepartmentUser;
    }
    
    /** 
    * __________________________________________________________________________
    * 
    * This method is used for getting approval process data     
    * _________________________________________________________________________
    * 
    * @param       recId                             Id
    * @return      List<ApprovalHistoryWrapper>
    * __________________________________________________________________________
    */
    public static List<ApprovalHistoryWrapper> getApprovalHistoryList(Id recId){      
        Id recordId = recId;         
        List<ApprovalHistoryWrapper> approvalHistoryWrapperList = new List<ApprovalHistoryWrapper>();
        for(ProcessInstance processInstance: getProcessHistory(recordId).values()){                   
            Map<Id, String> reassignCommentsMap = new Map<Id, String>(); 
            List<CalSTA_Reassign_Comments__c> reassignComments = [SELECT Id, Name, ProcessStepId__c, TargetObjectId__c,Comments__c FROM CalSTA_Reassign_Comments__c where TargetObjectId__c =:recordId];
            for(CalSTA_Reassign_Comments__c Comments : reassignComments){
                reassignCommentsMap.put(Comments.ProcessStepId__c, Comments.Comments__c);               
            }
           	String comments = null;
            String stepStatus =null;
            String assignedByName = null;
            String actorName = null; 
            String originalactorName =null;
            for(ProcessInstanceHistory sWI:processInstance.StepsAndWorkitems) {  
                if( sWI.comments == null){
                    comments = reassignCommentsMap.get(sWI.Id);
                }else{
                    comments = sWI.comments;
                }				
                if(sWI.ProcessNode.Name == 'Reviewer Action' && sWI.StepStatus == 'Rejected'){
                    stepStatus = 'Revision';
                }else if(sWI.ProcessNode.Name == 'Approver Action' && sWI.StepStatus == 'Rejected'){
                    stepStatus = 'Re-evaluation';
                }else if(sWI.ProcessNode.Name == 'Reviewer Action' && sWI.StepStatus == 'Approved'){
                    stepStatus = 'Reviewed';
                }else{
                    stepStatus = sWI.StepStatus;
                }
                
                if(sWI.StepStatus == 'Started'){
                    originalactorName ='';
                }else{
                    originalactorName = sWI.OriginalActor.Name;
                }
                
                 if(sWI.StepStatus == 'Started' || stepStatus == 'Reviewed' || sWI.StepStatus == 'Approved'){
                    actorName = '';
                    assignedByName = sWI.Actor.Name; 
                }
                else if(sWI.StepStatus == 'Reassigned'){
                    assignedByName = sWI.CreatedBy.Name;    
                    actorName = sWI.Actor.Name;
                }else if(stepStatus == 'Revision' || stepStatus == 'Re-evaluation'){
                    assignedByName = sWI.Actor.Name;                     
                    actorName = '';
                }else{                           
                    assignedByName = ''; 
                    actorName = sWI.Actor.Name;                   
                }   
                
                if(sWI.StepStatus == 'Started'){
                    approvalHistoryWrapperList.add(new ApprovalHistoryWrapper(sWI.CreatedDate, originalactorName, 'Submitted',actorName, comments,'Approval Request Submitted',sWI.OriginalActorId,sWI.ActorId,sWI.Id,assignedByName,sWI.TargetObjectId)); 
                }else{
                    approvalHistoryWrapperList.add(new ApprovalHistoryWrapper(sWI.CreatedDate, originalactorName, stepStatus,actorName, comments,sWI.ProcessNode.Name,sWI.OriginalActorId,sWI.ActorId,sWI.Id,assignedByName,sWI.TargetObjectId)); 
                } 
             }                   
        }      
             
        return approvalHistoryWrapperList;         
    }  
    
    /** 
    * __________________________________________________________________________
    * 
    * This method is used for getting approval data using SOQL query     
    * _________________________________________________________________________
    * 
    * @param       objectId                             Id
    * @return      Map<Id,ProcessInstance>
    * __________________________________________________________________________
    */
    public static Map<Id,ProcessInstance> getProcessHistory(Id objectId){  
        return new Map<Id,ProcessInstance>([SELECT Id,Status,SubmittedById, (SELECT Id, ProcessNodeId, StepStatus, Comments, TargetObjectId,ActorId,CreatedById,IsDeleted,IsPending ,OriginalActorId,ProcessInstanceId,RemindersSent,CreatedDate, Actor.Name, OriginalActor.Name ,CreatedBy.Name, ProcessNode.Name FROM StepsAndWorkitems order by IsPending DESC, CreatedDate DESC ) 
                                            FROM ProcessInstance where TargetObjectId =: objectId order by CreatedDate DESC]);  
    }  
    
     /** _____________________________________________
     * 
	 *	 This class is used for declaring variables 
	 *  _______________________________________________
     */    
    public class ApprovalHistoryWrapper{ 
        
	    public DateTime createdDate {get;set;}         
        
        public string assignedTo {get;set;}        
       
        public string steps {get;set;}         
          
        public string actualApprovar {get;set;}        
        
        public string comments {get;set;}         
        
        public string processNode {get;set;}         
         
        public string OriginalActorId {get;set;}         
      
        public string ActualActorId {get;set;}         
        
        public string InstanceStepId {get;set;}      
       
        public string assignedBy {get;set;}
       
        public string TargetobjId {get;set;}       
        
         /* _____________________________________________
         * 
         *	 This contructor  is used for assigning values to variables
         *  _______________________________________________
         */
        public ApprovalHistoryWrapper(DateTime crDate, string name, string stp, string actor, string commnets, string processName, string OriginalId, string ActorId, string stepid,string assignedByName,string TargetId) {  
            createdDate = crDate;  
            assignedTo = name;  
            steps = stp;  
            actualApprovar = actor; 
            comments = commnets;
            processNode = processName;
            OriginalActorId = OriginalId;
            ActualActorId = ActorId;
            InstanceStepId = stepid;
            assignedBy = assignedByName;
            TargetobjId = TargetId;
        }  
    }  
    
}