force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Action_requested__c</fullName>
        <label>Action Requested</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>For Information Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approve_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Secretory Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Reply from Approver 2</fullName>
                    <isActive>false</isActive>
                    <label>Reply from Approver 2</label>
                </value>
                <value>
                    <fullName>Request for Approver 1</fullName>
                    <isActive>false</isActive>
                    <label>Request for Approver 1</label>
                </value>
                <value>
                    <fullName>Request from Approver1 to Approver 2</fullName>
                    <isActive>false</isActive>
                    <label>Request from Approver1 to Approver 2</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_IM__c</fullName>
        <inlineHelpText>Click the calendar icon to select a date or enter using the format mm/dd/yyyy</inlineHelpText>
        <label>Date of IM</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <description>Reviewer is the field where we need to retrieve reviewer in approval process</description>
        <label>Reviewer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CALSTA_Batch_Email_Reminder_Test.cls
@isTest
public class CALSTA_Batch_Email_Reminder_Test {
   
    @testSetup
    static void calledGroupAndGroupMembers(){
    	
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        //creating user
        String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+RandomId; 
        User user1=new User(firstname = 'ABC',lastName = 'XYZ',email = uniqueName + '@test' + orgId + '.org', 
                         Username = uniqueName + '@test' + orgId + '.org', 
                         EmailEncodingKey = 'ISO-8859-1',Alias = uniqueName.substring(18, 23), 
                         TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US',ProfileId = pf.Id);
        insert user1;
        
        //creating group
    	Group testGroup = new Group();
        testGroup.Name = 'abctest';
        testGroup.Type='Queue';
        testGroup.DeveloperName = 'ABCD';
        insert testGroup; 
        //Creating Group Members
        GroupMember grpMem = new GroupMember();
        grpMem.UserOrGroupId =user1.id;
        grpMem.GroupId = testGroup.id;
        insert grpMem;
        
        
}
    
    static testmethod void emailReminderCalledFunction1(){
       
        Account acc=new Account();
        acc.Name='Department of Transportation';
        insert acc;
              
        ID getRecordTypeId=Schema.SObjectType.Case.getRecordTypeInfosByName().get('Governor’s Office Action Request (GOAR)').getRecordTypeId();
        
       
        //fetching group details
        Group gp=[SELECT Id,Name FROM Group where group.name=:'abctest'];
      	system.debug(gp.name);
        //creating case record
        Case obj=new Case();
        obj.AccountId=acc.id;
        obj.Subject='Test2';
        obj.Action_requested__c='Approval';
        obj.Approve_Status__c='Draft';
        obj.RecordTypeId=getRecordTypeId;
        obj.Date_of_IM__c=date.today();
        obj.Reviewer__c=gp.name;
        insert obj;
       
       
        CALSTA_Batch_Email_Notification_Reminder executeJob=new CALSTA_Batch_Email_Notification_Reminder();
        test.startTest();
        Database.executeBatch(executeJob);
        test.stopTest();
        
        
        }
    static testmethod void emailReminderCalledFunction2(){
       Account acc=new Account();
        acc.Name='Department of Transportation';
        insert acc;
        
        ID getRecordTypeId=Schema.SObjectType.Case.getRecordTypeInfosByName().get('Governor’s Office Action Request (GOAR)').getRecordTypeId();
         
        //Fetching user details
       user u1=[select id,name from user where user.name=:'ABC XYZ'];
       //creating case record
        Case obj=new Case();
        obj.AccountId=acc.id;
        obj.Subject='Test2';
        obj.Action_requested__c='Approval';
        obj.Approve_Status__c='Draft';
        obj.RecordTypeId=getRecordTypeId;
        obj.Date_of_IM__c=date.today();
      	obj.Reviewer__c=u1.name;
        insert obj;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(obj.id);
        
        
        // Submit on behalf of a specific submitter
        req1.setSubmitterId(u1.Id); 
        
        // Submit the record to specific process and skip the criteria evaluation
        //req1.setProcessDefinitionNameOrId('PTO_Request_Process');
        req1.setSkipEntryCriteria(true);
        
        // Submit the approval request for the case
        Approval.ProcessResult result = Approval.process(req1);
        System.assert(result.isSuccess());
		        
        System.assertEquals('Pending', result.getInstanceStatus());
        
        CALSTA_Batch_Email_Notification_Reminder executeJob=new CALSTA_Batch_Email_Notification_Reminder();
        test.startTest();
        Database.executeBatch(executeJob);
        test.stopTest();
        
        }
    

}